### ISSUE TITLE
Uncaught Error: Undefined constant "Akash\JobPlace\Setup\CART_PULSE_VERSION"

### ISSUE THREAD

**Issue by MaxFry** [ManiruzzamanAkash/wp-react-kit#11]
Hello, I decided to look at your project. but ran into this error: Uncaught Error: Undefined constant "Akash\JobPlace\Setup\CART_PULSE_VERSION"  includs/installer.php:65. Perhaps I made a mistake somewhere in the installation.

I just added it in the installer class and it worked. but I don't know what it should be

**Comment by maniruzzamancse** [comment]
Is the issue fixed ?

**Comment by ManiruzzamanAkash** [comment]
@maniruzzamancse Yes, That was a issue for constant data which was used previously. That has bee removed now.

**Comment by maniruzzamancse** [comment]
> @maniruzzamancse Yes, That was a issue for constant data which was used previously. That has bee removed now.

Thank you.
