### ISSUE TITLE
Enzyme is dead.

### ISSUE THREAD

**Issue by aczire** [ManiruzzamanAkash/wp-react-kit#15]
Enzyme is dead, as per the blog here. So if any one want to make use of the new shiny React-18, there is no way.
https://dev.to/wojtekmaj/enzyme-is-dead-now-what-ekl
There are other problems as well. Ref: https://github.com/WordPress/gutenberg/issues/17249

It would be nice to get rid of Enzyme for once and for all.

**Comment by ManiruzzamanAkash** [comment]
Ok, we're keeping that an Enhancement for next.
